[package]
name = "segul"
version = "0.2.0"
authors = ["Heru Handika <herubiolog@gmail.com>"]
edition = "2018"

[dependencies]
alphanumeric-sort = "1.4.*"
anyhow = "1.0.*"
bytecount = "0.6.2"
chrono = "0.4.*"
clap = "2.*"
glob = "*"
indexmap = "1.6.*"
indicatif = "0.16.*"
nom = "6.*"
num-format = "0.4.*"
rayon = "*"


