[package]
name = "segul"
version = "0.16.3"
authors = ["Heru Handika <herubiolog@gmail.com>"]
edition = "2021"
license = "MIT"
description = "An ultrafast and memory efficient alignment tool for phylogenomics"
readme = "README.md"
homepage = "https://github.com/hhandika/segul"
repository = "https://github.com/hhandika/segul"
keywords = ["cli", "utility", "alignment", "genomics", "phylogenomics"]
categories = ["command-line-utilities", "science"]

[dependencies]
ahash = "0.*"
alphanumeric-sort = "1.*"
ansi_term = "0.*"
anyhow = "1.*"
bytecount = "0.*"
chrono = "0.*"
clap = { version = "3.*", features = ["cargo"] }
dialoguer = "0.*"
glob = "0.3.*"
indexmap = "1.*"
indicatif = "0.*"
lazy_static = "1.*"
log = "0.*"
log4rs = "1.*"
nom = "6.*"
num-format = "0.*"
rayon = "1.*"
regex = "1.*"

[profile.release]
debug = false
lto = "fat"
panic = "abort"