[package]
name = "segul"
version = "0.1.0"
authors = ["Heru Handika <herubiolog@gmail.com>"]
edition = "2018"

[dependencies]
clap = "*"
nom = "6.*"
glob = "*"
indexmap = "1.6.*"
rayon = "*"
num-format = "0.4.*"
indicatif = "0.16.*"