[package]
name = "segul"
version = "0.1.0"
authors = ["Heru Handika <herubiolog@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
nom = "6.*"
glob = "*"
indexmap = "1.6.*"

# linked-hash-map = "0.5.4"
# linked_hash_set = "0.1.4"