[package]
name = "segul"
version = "0.3.6"
authors = ["Heru Handika <herubiolog@gmail.com>"]
edition = "2018"
license = "MIT"
description = "An ultrafast and memory efficient alignment tool for phylogenomics"
readme = "README.md"
homepage = "https://github.com/hhandika/segul"
repository = "https://github.com/hhandika/segul"
keywords = ["cli", "utility", "alignment", "genomics", "phylogenomics"]
categories = ["command-line-utilities", "science"]

[dependencies]
ahash = "0.7.4"
alphanumeric-sort = "1.4.*"
ansi_term = "0.12.1"
anyhow = "1.0.*"
bytecount = "0.6.2"
chrono = "0.4.*"
clap = "2.*"
glob = "0.3.*"
indexmap = "1.6.*"
indicatif = "0.16.*"
lazy_static = "1.4.0"
log = "0.4.14"
log4rs = "1.0.0"
nom = "6.*"
num-format = "0.4.*"
rayon = "1.5.*"
regex = "1.4.5"

[profile.release]
debug = false
lto = "fat"
