name: segul
base: core20 # the base snap is the execution environment for this snap
version: "0.21.3"
summary: A phylogenomic data manipulation and summary statistic tool # 79 char long summary
description: |
  SEGUL is an ultrafast, memory efficient, 
  cross-platform tool for phylogenomic data manipulation and summary statistics calculation.

grade: stable
confinement: strict
architectures:
  - build-on: ["amd64", "arm64", "armhf", "ppc64el", "s390x"]

slots:
  segul:
    interface: dbus
    bus: session
    name: com.hhandika.segul

apps:
  segul:
    command: bin/segul
    plugs:
      - home
      - removable-media
      - cifs-mount

parts:
  segul:
    source: .
    plugin: rust
